accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register_user', views.register_user, name='register_user'),
    path('register_vendor', views.register_vendor, name='register_vendor'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('my_account/', views.my_account, name='my_account'),
    path('cust_dashboard/', views.cust_dashboard, name='cust_dashboard'),
    path('vendor_dashboard/', views.vendor_dashboard, name='vendor_dashboard'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('reset_password_validate/<uidb64>/<token>/', views.reset_password_validate, name='reset_password_validate'),
    path('reset_password/', views.reset_password, name='reset_password'),
]

foodOnline_main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/alerts.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} show-notification" role="alert">
            <button type="button" class="close"  data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true" >&times</span>
            </button>
            <strong>{{ message }}</strong>
        </div>
    {% endfor %}

{% endif %}

templates/includes/footer.html
{% load static %}
<!-- Footer Start -->
		<footer id="footer" class="footer-style-2">
			<div class="footer-widget">
				<div class="container">
					<div class="row">
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
							<div class="widget widget-newsletter">
								<div class="widget-title">
									<h5>Subscribe to our Newsletter</h5>
								</div>
								<div class="fieldset">
									<form action="#">
										<div class="field-holder">
											<label>
												<i class=" icon-envelope3"></i>
												<input type="text" class="field-input" placeholder=" Enter Your Email Address...">
											</label>
										</div>
										<div class="field-holder btn-holder">
											<input class="subscribe-btn bgcolor" type="submit" value="Sign Up">
										</div>
									</form>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="copyright-sec">
				<div class="container">
					<div class="row">
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
							<div class="copyright-inner">
								<div class="copy-right">
									<p>© 2020 Foodbakery. All Rights Reserved. Developed By <a href="#">Rathan Kumar</a>
									</p>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div> <!-- /.cs-copyright -->
		</footer>
		<!-- Footer End -->


	<!-- Modal Popup End -->
	<script src="{% static '' %}assets/js/scripts.js"></script>
	<script src="{% static '' %}assets/js/functions.js"></script>
</body>

</html>


templates/includes/navbar.html
{% load static %}
<!--Main Wrapper-->
<div class="wrapper">
    <!-- Header Start -->
    <header id="header">
        <div class="main-header">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
                        <div class="logo">
                            <figure>
                                <a href="{% url 'home' %}" class="light-logo">
                                    <img src="{% static '' %}assets/logo/foodOnlineLogo.png" alt="FoodBakery"
                                         width="250px">
                                </a>
                            </figure>
                        </div>


                        <div class="main-location ml-5">
                            <ul>
                                <li class="location-has-children choose-location">
                                    <form action="#">
                                        <input type="text" value="" name="location"
                                               placeholder="Enter your delivery location" autocomplete="off">
                                        <span id="foodbakery_radius_location_open" class="foodbakery-radius-location"><i
                                                class="icon-target5"></i></span>
                                    </form>

                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                        <div class="login-option">
                            {% if user.is_authenticated %}
                                <a class="cs-color cs-popup-joinus-btn login-popup" href="{% url 'accounts:my_account' %}">My Account</a>
                                <a class="cs-color cs-popup-joinus-btn login-popup text-danger" href="{% url 'accounts:logout' %}">Logout</a>
                            {% else %}
                                <a class="cs-color cs-popup-joinus-btn login-popup" href="{% url 'accounts:login' %}">Login</a>
                                /
                                <span><a href="{% url 'accounts:register_user' %}"
                                         class="cs-color cs-popup-joinus-btn login-popup ml-0">Register</a></span></a>
                                <a class="get-start-btn" href="{% url 'accounts:register_vendor' %}">
                                    Register
                                    Restaurant </a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- Header End -->
</div>